-- =========================================================
-- PT JAYA TEKNIS - DATABASE BACKUP DUMP
-- Database      : jaya_teknik
-- Generated At  : 2026-09-15 12:51:33
-- Generated By  : Administrator (Administrator)
-- Target Scope  : ALL TABLES
-- Description   : Transaksi Kosongan
-- =========================================================

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+08:00";


-- --------------------------------------------------------
-- Table structure for table `activity_log`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `activity_log`;
CREATE TABLE `activity_log` (
  `id_log` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id_karyawan` int(11) DEFAULT NULL,
  `nama_pengguna` varchar(100) NOT NULL,
  `role` varchar(30) NOT NULL,
  `modul` varchar(50) NOT NULL,
  `aksi` varchar(50) NOT NULL,
  `id_referensi` int(11) DEFAULT NULL,
  `nomor_referensi` varchar(50) DEFAULT NULL,
  `deskripsi` text NOT NULL,
  `data_sebelumnya` longtext DEFAULT NULL,
  `data_sesudahnya` longtext DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_log`),
  KEY `idx_karyawan` (`id_karyawan`),
  KEY `idx_modul_aksi` (`modul`,`aksi`),
  KEY `idx_referensi` (`modul`,`id_referensi`),
  KEY `idx_nomor_referensi` (`nomor_referensi`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- --------------------------------------------------------
-- Table structure for table `adjustment_stok`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `adjustment_stok`;
CREATE TABLE `adjustment_stok` (
  `id_adjustment` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_adjustment` varchar(30) NOT NULL,
  `tanggal_adjustment` datetime NOT NULL,
  `id_site` int(11) NOT NULL,
  `jenis_adjustment` enum('PENAMBAHAN','PENGURANGAN','SET_STOK') NOT NULL,
  `alasan` varchar(255) NOT NULL,
  `keterangan` text DEFAULT NULL,
  `status` enum('DRAFT','PENDING','APPROVED','REJECTED','BATAL') NOT NULL DEFAULT 'DRAFT',
  `id_karyawan` int(11) NOT NULL,
  `id_karyawan_approved` int(11) DEFAULT NULL,
  `tanggal_approved` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_adjustment`),
  UNIQUE KEY `nomor_adjustment` (`nomor_adjustment`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `adjustment_stok_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `adjustment_stok_detail`;
CREATE TABLE `adjustment_stok_detail` (
  `id_adjustment_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_adjustment` int(11) NOT NULL,
  `id_barang` int(11) NOT NULL,
  `qty_sistem` double DEFAULT 0,
  `qty_fisik` double DEFAULT 0,
  `qty_adjustment` double DEFAULT 0,
  `qty_akhir` double DEFAULT 0,
  `keterangan` text DEFAULT NULL,
  `harga_satuan` double DEFAULT 0,
  `subtotal_adjustment` double DEFAULT 0,
  PRIMARY KEY (`id_adjustment_detail`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `backup`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `backup`;
CREATE TABLE `backup` (
  `id_backup` int(11) NOT NULL AUTO_INCREMENT,
  `email_backup` varchar(50) DEFAULT NULL,
  `tanggal_backup` datetime DEFAULT current_timestamp(),
  `id_karyawan` varchar(255) DEFAULT NULL,
  `scope` text DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `lokasi` varchar(255) DEFAULT NULL COMMENT 'tersimpan difolder project untuk kebutuhan restore',
  `nama_file` varchar(50) DEFAULT NULL,
  `id_karyawan_restore` int(11) DEFAULT NULL COMMENT 'yang melakukan restore',
  `tanggal_restore` datetime DEFAULT NULL,
  PRIMARY KEY (`id_backup`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `backup` (1 rows)
INSERT INTO `backup` (`id_backup`, `email_backup`, `tanggal_backup`, `id_karyawan`, `scope`, `keterangan`, `lokasi`, `nama_file`, `id_karyawan_restore`, `tanggal_restore`) VALUES
('1', 'itdev.nuansa@gmail.com', '2026-09-11 15:31:01', 'Administrator', 'ALL', '', 'backups/backup_db_jaya_teknik_20260911_153101.sql', 'backup_db_jaya_teknik_20260911_153101.sql', NULL, NULL);


-- --------------------------------------------------------
-- Table structure for table `barang`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `barang`;
CREATE TABLE `barang` (
  `id_barang` int(11) NOT NULL AUTO_INCREMENT,
  `kode_barang` varchar(30) DEFAULT NULL,
  `id_merk` int(11) DEFAULT 1,
  `id_kategori` int(11) DEFAULT 1,
  `default_id_vendor` int(11) DEFAULT NULL,
  `nama_barang` varchar(60) NOT NULL DEFAULT '1',
  `jenis` tinyint(1) DEFAULT 1 COMMENT '1 = Persediaan , 0 = Jasa',
  `satuan` varchar(30) NOT NULL DEFAULT 'PCS',
  `asset` tinyint(1) DEFAULT 0 COMMENT '1 = Asset, 0 = Bukan Asset',
  `serial_number` varchar(30) DEFAULT NULL,
  `foto1` varchar(50) DEFAULT NULL,
  `foto2` varchar(50) DEFAULT NULL,
  `deskripsi` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `id_karyawan` int(11) NOT NULL,
  `aktif` tinyint(4) DEFAULT 1,
  `PPnBM` tinyint(1) DEFAULT 0 COMMENT '1=mewah , 0 tidak',
  `rate_PPnBM` double DEFAULT 0,
  PRIMARY KEY (`id_barang`),
  KEY `idx_barang_nama` (`nama_barang`),
  KEY `idx_barang_kode` (`kode_barang`),
  KEY `idx_barang_aktif` (`aktif`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `barang` (25 rows)
INSERT INTO `barang` (`id_barang`, `kode_barang`, `id_merk`, `id_kategori`, `default_id_vendor`, `nama_barang`, `jenis`, `satuan`, `asset`, `serial_number`, `foto1`, `foto2`, `deskripsi`, `created_at`, `id_karyawan`, `aktif`, `PPnBM`, `rate_PPnBM`) VALUES
('1', 'BRG001', '1', '1', '2', 'Kawat Las LB-52 3.2mm Kobe Steel', '1', 'PCS', '0', NULL, NULL, NULL, 'Kawat las elektroda untuk lambung kapal & konstruksi berat', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('2', 'BRG002', '1', '1', '1', 'Plat Baja Marine Grade AH36 12mm x 5ft x 20ft', '1', 'UNIT', '0', NULL, NULL, NULL, 'Plat baja standar lambung kapal bersertifikat BKI/LR', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('3', 'BRG003', '1', '1', '1', 'Pipa Seamless Carbon Steel Sch 80 4 Inch', '1', 'PCS', '0', '', '', '', 'Pipa jalur bahan bakar & pendingin kapal', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('4', 'BRG004', '1', '1', '2', 'Mata Bubut Sandvik Coromant CNMG 120408', '1', 'PCS', '0', NULL, NULL, NULL, 'Insert bubut bubut as propeller dan shaft', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('5', 'BRG005', '1', '1', '3', 'Bearing Spherical Roller SKF 22220 EK', '1', 'PCS', '0', NULL, NULL, NULL, 'Bearing poros baling-baling kapal', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('6', 'BRG006', '1', '1', '4', 'Bronze Marine Globe Valve 3 Inch Flange PN16', '1', 'PCS', '0', NULL, NULL, NULL, 'Valve laut tahan korosi air asin', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('7', 'BRG007', '1', '1', '2', 'Mata Bor HSS Morse Taper 25mm Nachi', '1', 'PCS', '0', NULL, NULL, NULL, 'Mata bor mesin radial drill bengkel bubut', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('8', 'BRG008', '1', '1', '4', 'Cat Antifouling Jotun SeaForce 90 20L', '1', 'UNIT', '0', '', '', '', 'Cat bawah lambung kapal pencegah teritip', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('9', 'BRG0009', '3', '5', NULL, 'Imola 500 (2.5 HP)', '1', 'UNIT', '1', '', NULL, NULL, NULL, '2026-09-12 10:32:29', '1', '1', '0', '0'),
('10', 'BRG0010', '1', '1', '4', 'Marine Steel Plate', '1', 'PCS', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0001', '2026-09-12 10:32:29', '2', '1', '0', '0'),
('11', 'BRG0011', '1', '1', '4', 'Cat Marine', '1', 'PCS', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0001', '2026-09-12 10:32:29', '2', '1', '0', '0'),
('12', 'BRG0012', '1', '1', '4', 'Tali Baja', '1', 'PCS', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0001', '2026-09-12 10:32:29', '2', '1', '0', '0'),
('13', 'BRG0013', '1', '1', '5', 'MT NEMO - MEJA KERJA', '1', 'UNIT', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0003', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('14', 'BRG0014', '159', '10', '5', 'KURSI KANTOR', '1', 'UNIT', '1', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0003', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('15', 'BRG0015', '1', '1', NULL, 'Baja Karbon', '1', 'MTR', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2608-0004', '2026-09-12 10:32:29', '2', '1', '0', '0'),
('16', 'BRG0016', '166', '13', '6', 'Kabel LAN CAT 6', '1', 'PCS', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0001', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('17', 'BRG0017', '1', '1', '6', 'HDMI 10m', '1', 'PCS', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0002', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('18', 'BRG0018', '1', '1', '7', 'Pintu Costum', '1', 'SET', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0003', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('19', 'BRG0019', '165', '10', '7', 'Kloset Duduk Dua Bagian CW420J', '1', 'UNIT', '1', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0003', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('20', 'BRG0020', '164', '10', '8', 'Homedoki', '1', 'UNIT', '1', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0004', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('21', 'BRG0021', '101', '23', '2', 'Bosch Impact Drill GSB 600', '1', 'UNIT', '1', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0005', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('22', 'BRG0022', '42', '14', '6', 'Printer EPSON L325', '1', 'UNIT', '0', '', NULL, NULL, 'Ditambahkan otomatis dari Request Order RO-2609-0006', '2026-09-12 10:32:29', '3', '1', '0', '0'),
('23', 'BRG0023', '42', '18', NULL, 'Epson XB300', '1', 'UNIT', '1', '', NULL, NULL, '', '2026-09-12 10:32:29', '1', '1', '0', '0'),
('24', 'BRG0024', '167', '7', NULL, 'Toyota Alphard 2.5 G', '1', 'UNIT', '1', 'KT 31 JS', NULL, NULL, 'Kendaraan entertaiment bos', '2026-09-12 10:42:16', '1', '1', '1', '25'),
('25', 'BRG0025', '167', '7', NULL, 'Lexus X7', '1', 'UNIT', '1', NULL, NULL, NULL, NULL, '2026-09-12 11:54:10', '1', '1', '1', '35');


-- --------------------------------------------------------
-- Table structure for table `barang_hargavendor`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `barang_hargavendor`;
CREATE TABLE `barang_hargavendor` (
  `id_harga` int(11) NOT NULL AUTO_INCREMENT,
  `id_barang` int(11) DEFAULT NULL,
  `id_vendor` int(11) DEFAULT NULL,
  `harga_set` double DEFAULT NULL,
  `berlaku` date DEFAULT NULL,
  PRIMARY KEY (`id_harga`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `barang_hargavendor` (3 rows)
INSERT INTO `barang_hargavendor` (`id_harga`, `id_barang`, `id_vendor`, `harga_set`, `berlaku`) VALUES
('11', '3', '4', '20000', '2026-08-20'),
('12', '3', '3', '15000', '2026-08-20'),
('13', '11', '4', '250000', '2026-08-22');


-- --------------------------------------------------------
-- Table structure for table `barang_stok`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `barang_stok`;
CREATE TABLE `barang_stok` (
  `id_stok` int(11) NOT NULL AUTO_INCREMENT,
  `id_barang` int(11) NOT NULL,
  `id_site` int(11) NOT NULL,
  `stok` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_stok`),
  UNIQUE KEY `uq_barang_site` (`id_barang`,`id_site`)
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `barang_stok` (65 rows)
INSERT INTO `barang_stok` (`id_stok`, `id_barang`, `id_site`, `stok`) VALUES
('25', '3', '3', '0'),
('26', '3', '2', '0'),
('27', '3', '1', '2'),
('28', '9', '3', '0'),
('29', '9', '2', '0'),
('30', '9', '1', '0'),
('31', '10', '1', '0'),
('32', '10', '2', '0'),
('33', '10', '3', '0'),
('34', '11', '1', '0'),
('35', '11', '2', '0'),
('36', '11', '3', '0'),
('37', '12', '1', '0'),
('38', '12', '2', '0'),
('39', '12', '3', '0'),
('40', '1', '1', '2'),
('41', '1', '3', '10'),
('42', '13', '1', '0'),
('43', '13', '2', '0'),
('44', '13', '3', '0'),
('45', '14', '1', '0'),
('46', '14', '2', '0'),
('47', '14', '3', '0'),
('48', '14', '4', '3'),
('50', '13', '4', '3'),
('51', '15', '1', '0'),
('52', '15', '2', '0'),
('53', '15', '3', '10'),
('54', '15', '4', '0'),
('55', '16', '1', '0'),
('56', '16', '2', '0'),
('57', '16', '3', '0'),
('58', '16', '4', '1'),
('59', '17', '1', '0'),
('60', '17', '2', '1'),
('61', '17', '3', '0'),
('62', '17', '4', '1'),
('63', '18', '1', '0'),
('64', '18', '2', '0'),
('65', '18', '3', '1'),
('66', '18', '4', '0'),
('67', '19', '1', '0'),
('68', '19', '2', '0'),
('69', '19', '3', '0'),
('70', '19', '4', '0'),
('71', '20', '1', '0'),
('72', '20', '2', '0'),
('73', '20', '3', '0'),
('74', '20', '4', '0'),
('75', '21', '1', '0'),
('76', '21', '2', '0'),
('77', '21', '3', '0'),
('78', '21', '4', '0'),
('79', '22', '1', '0'),
('80', '22', '2', '0'),
('81', '22', '3', '0'),
('82', '22', '4', '0'),
('83', '23', '4', '0'),
('84', '23', '3', '0'),
('85', '23', '2', '0'),
('86', '23', '1', '0'),
('89', '24', '4', '1'),
('90', '24', '3', '0'),
('91', '24', '2', '0'),
('92', '24', '1', '0');


-- --------------------------------------------------------
-- Table structure for table `divisi`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `divisi`;
CREATE TABLE `divisi` (
  `id_divisi` int(11) NOT NULL AUTO_INCREMENT,
  `kode_divisi` varchar(10) DEFAULT NULL,
  `nama_divisi` varchar(50) DEFAULT NULL,
  `level` tinyint(1) DEFAULT NULL,
  `id_karyawan_headof` int(11) DEFAULT NULL COMMENT 'jadikan approval',
  PRIMARY KEY (`id_divisi`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `divisi` (6 rows)
INSERT INTO `divisi` (`id_divisi`, `kode_divisi`, `nama_divisi`, `level`, `id_karyawan_headof`) VALUES
('1', 'DIV01', 'Manajemen', '1', '5'),
('2', 'DIV02', 'Logistik & Gudang', '2', NULL),
('3', 'DIV03', 'Purchasing & Pengadaan', '2', NULL),
('4', 'DIV04', 'Bengkel Las & Bubut (Mekanik)', '3', NULL),
('5', 'DIV05', 'IT & Administrasi', '2', '6'),
('6', 'DIV06', 'Finance', '2', '9');


-- --------------------------------------------------------
-- Table structure for table `faktur_po`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `faktur_po`;
CREATE TABLE `faktur_po` (
  `id_faktur` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_faktur` varchar(25) NOT NULL,
  `nomor_faktur_vendor` varchar(50) NOT NULL COMMENT 'nomor invoice vendor',
  `nomor_faktur_pajak` varchar(30) DEFAULT NULL,
  `tanggal_faktur_pajak` date DEFAULT NULL,
  `tanggal_faktur_vendor` date NOT NULL COMMENT 'tanggal invoice vendor',
  `tanggal_terima_faktur_vendor` date NOT NULL COMMENT 'tanggal invoice datang ke perusahaan/pembeli',
  `term_of_payment` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'default mengikuti purchase_order.term_of_payment',
  `tanggal_jatuh_tempo` date NOT NULL COMMENT 'hitung hari dari term_of_payment',
  `id_po` int(11) NOT NULL,
  `id_rcv` int(11) NOT NULL,
  `id_vendor` int(11) NOT NULL,
  `id_site` int(11) NOT NULL,
  `nama_bank` varchar(50) DEFAULT NULL,
  `nomor_rekening` varchar(40) DEFAULT NULL,
  `atas_nama_rekening` varchar(100) DEFAULT NULL,
  `id_karyawan` int(11) NOT NULL,
  `subtotal_po` double NOT NULL DEFAULT 0,
  `subtotal_diterima` double NOT NULL DEFAULT 0,
  `nilai_retur` double NOT NULL DEFAULT 0,
  `diskon` double NOT NULL DEFAULT 0,
  `rate_pajak` tinyint(4) NOT NULL DEFAULT 0 COMMENT 'PPN',
  `nominal_pajak` double NOT NULL DEFAULT 0 COMMENT 'PPN',
  `dpp` double NOT NULL DEFAULT 0,
  `rate_ppnbm` double DEFAULT NULL,
  `nominal_ppnbm` double DEFAULT NULL,
  `biaya_lain` double NOT NULL DEFAULT 0,
  `total_tagihan` double NOT NULL DEFAULT 0,
  `status` enum('DRAFT','BELUM DIBAYAR','SEBAGIAN DIBAYAR','LUNAS','BATAL') NOT NULL DEFAULT 'BELUM DIBAYAR',
  `terbayar` double NOT NULL DEFAULT 0,
  `sisa_tagihan` double NOT NULL DEFAULT 0,
  `file_faktur_vendor` varchar(255) DEFAULT NULL,
  `file_faktur_pajak` varchar(255) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_faktur`),
  UNIQUE KEY `uk_nomor_faktur` (`nomor_faktur`),
  KEY `idx_id_po` (`id_po`),
  KEY `idx_id_rcv` (`id_rcv`),
  KEY `idx_id_vendor` (`id_vendor`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `faktur_po_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `faktur_po_detail`;
CREATE TABLE `faktur_po_detail` (
  `id_faktur_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_faktur` int(11) NOT NULL,
  `id_barang` int(11) NOT NULL,
  `qty_po` double NOT NULL DEFAULT 0,
  `qty_rcv` double NOT NULL DEFAULT 0,
  `qty_retur` double NOT NULL DEFAULT 0,
  `qty_tagih` double NOT NULL DEFAULT 0,
  `satuan` varchar(20) NOT NULL,
  `harga_satuan` double NOT NULL DEFAULT 0,
  `diskon_item` double NOT NULL DEFAULT 0,
  `subtotal` double NOT NULL DEFAULT 0,
  `keterangan` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_faktur_detail`),
  KEY `idx_id_faktur` (`id_faktur`),
  KEY `idx_id_barang` (`id_barang`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `info`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `info`;
CREATE TABLE `info` (
  `id_info` int(11) NOT NULL AUTO_INCREMENT,
  `judul` varchar(60) DEFAULT NULL,
  `isi` text DEFAULT NULL,
  `file` varchar(100) DEFAULT NULL,
  `aktif` tinyint(4) DEFAULT 1,
  `id_karyawan` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `divisi_array` varchar(255) DEFAULT NULL COMMENT 'terlihat oleh divisi\r\ncontoh input\r\n1,2,3',
  `tampil_login` tinyint(1) DEFAULT 0 COMMENT '1 = ya , 0 tidak',
  PRIMARY KEY (`id_info`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `info` (2 rows)
INSERT INTO `info` (`id_info`, `judul`, `isi`, `file`, `aktif`, `id_karyawan`, `created_at`, `divisi_array`, `tampil_login`) VALUES
('1', 'Jadwal Maintenance', 'Akan dilakukan maintenance sistem berkala pada hari Sabtu pukul 22:00 - 24:00 WIB.', '', '1', '1', '2026-09-12 08:56:59', '1,2,3,4,5', '1'),
('2', 'Pemberitahuan Pengadaan Barang Q3', 'Seluruh kepala unit dan mekanik diharapkan mengajukan RO paling lambat akhir bulan ini.', '', '1', '1', '2026-08-22 13:12:22', '3,4', '0');


-- --------------------------------------------------------
-- Table structure for table `jabatan`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `jabatan`;
CREATE TABLE `jabatan` (
  `id_jabatan` int(11) NOT NULL AUTO_INCREMENT,
  `kode_jabatan` varchar(10) DEFAULT NULL COMMENT 'Auto JB-001',
  `nama_jabatan` varchar(50) DEFAULT NULL,
  `id_divisi` int(11) DEFAULT NULL,
  `level` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id_jabatan`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `jabatan` (7 rows)
INSERT INTO `jabatan` (`id_jabatan`, `kode_jabatan`, `nama_jabatan`, `id_divisi`, `level`) VALUES
('1', 'JB-001', 'Administrator', '5', '1'),
('2', 'JB-002', 'Admin Logistik', '2', '3'),
('3', 'JB-003', 'Kepala Mekanik', '4', '2'),
('4', 'JB-004', 'Manager Cabang', '1', '1'),
('5', 'JB-005', 'Staff Purchasing', '3', '3'),
('6', 'JB-006', 'Staff Finance', '6', '3'),
('7', 'JB-007', 'Manager Finance', '6', '1');


-- --------------------------------------------------------
-- Table structure for table `karyawan`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `karyawan`;
CREATE TABLE `karyawan` (
  `id_karyawan` int(11) NOT NULL AUTO_INCREMENT,
  `kode_karyawan` varchar(255) DEFAULT NULL,
  `id_jabatan` int(11) DEFAULT NULL,
  `nama_karyawan` varchar(255) DEFAULT NULL,
  `id_divisi` int(11) NOT NULL,
  `tanggal_bergabung` datetime DEFAULT NULL,
  `aktif` tinyint(1) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `no_handphone` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `status_karyawan` tinyint(1) NOT NULL COMMENT 'Magang (Internship), PKWT (Perjanjian Kerja Waktu Tertentu), PKWTT (Perjanjian Kerja Waktu Tidak Tertentu), Pekerja paruh waktu (Part-time), Harian Lepas (Casual Workers), Freelance / Pekerja Lepas, Outsourcing / Alih Daya, Volunteer / Sukarelawan\r\n',
  `login_web` tinyint(1) DEFAULT NULL,
  `tanggal_lahir` date DEFAULT NULL,
  `tempat_lahir` varchar(30) DEFAULT NULL,
  `jenis_kelamin` tinyint(4) DEFAULT NULL COMMENT '1= Laki-Laki , 0 = Perempuan',
  `id_site` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_karyawan`,`status_karyawan`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `karyawan` (8 rows)
INSERT INTO `karyawan` (`id_karyawan`, `kode_karyawan`, `id_jabatan`, `nama_karyawan`, `id_divisi`, `tanggal_bergabung`, `aktif`, `email`, `no_handphone`, `password`, `status_karyawan`, `login_web`, `tanggal_lahir`, `tempat_lahir`, `jenis_kelamin`, `id_site`) VALUES
('2', 'KRY002', '3', 'Budi Jaya', '4', '2026-08-19 22:23:08', '1', 'mekanik@jayateknis.com', '081234567891', '$2y$10$leTW0vO08SPhmk1K0Dp97uaE9cQabEjTDnHMwPFg7cMPiQebUGxo.', '2', '1', '1993-08-25', 'Bontang', '1', '1'),
('3', 'KRY003', '2', 'Agus Hermawan', '2', '2026-08-19 22:23:08', '1', 'dosen.samsu@gmail.com', '081234567892', '$2y$10$.flc709mORDo9MgHEB1cHuhuPuSyg/dCWBo6fQ70h/OLGqzTxRZdq', '2', '1', '2000-12-05', 'Medan', '1', NULL),
('4', 'KRY004', '5', 'Siti Khodijah', '3', '2026-08-19 22:23:08', '1', 'sidaw37998@airhemp.com', '085512345678', '$2y$10$gXvuzhGeM6AmUDFDObJ8hOPaUp9BXUfQY77BO3cbV.v6zjRW/2Izu', '2', '1', '2000-01-03', 'Bandung', '2', NULL),
('5', 'KRY005', '4', 'Hendra', '1', '2026-08-19 22:23:08', '1', 'shem1990@gmail.com', '081234567894', '$2y$10$.flc709mORDo9MgHEB1cHuhuPuSyg/dCWBo6fQ70h/OLGqzTxRZdq', '2', '1', NULL, NULL, '1', '1'),
('6', 'KRY001', '1', 'Bambang Admin', '5', '2026-08-19 22:22:31', '1', 'admin@jayateknis.com', '081234567890', '$2y$10$gXvuzhGeM6AmUDFDObJ8hOPaUp9BXUfQY77BO3cbV.v6zjRW/2Izu', '2', '1', NULL, NULL, NULL, NULL),
('7', 'KRY006', '2', 'Seno', '2', '2026-08-26 09:35:59', '1', NULL, NULL, NULL, '2', '0', NULL, NULL, '1', '1'),
('8', 'KRY007', '6', 'Diana Putri', '6', '2026-08-29 14:02:33', '1', 'lopeki8543@airhemp.com', '081234567899', '$2y$10$GoLgk6w86qjKHbNkGvBrG.9MFSot493s/XtTwpZ5qkGzE/lUsBD7e', '1', '1', '1996-09-21', 'Balikpapan', '2', '1'),
('9', 'MGR-FIN', '7', 'Farhan Manager Finance', '6', '2026-08-29 14:21:38', '1', 'shem1990@gmail.com', '081298765432', '$2y$10$P.gQplvSM8e4HXzcj0dADOI7lQle6.Cnd1mZhcFOg5B7XQhfzq2fi', '1', '1', NULL, NULL, NULL, NULL);


-- --------------------------------------------------------
-- Table structure for table `kategori_barang`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `kategori_barang`;
CREATE TABLE `kategori_barang` (
  `id_kategori` int(11) NOT NULL AUTO_INCREMENT,
  `kode_kategori` varchar(10) DEFAULT NULL,
  `nama_kategori` varchar(50) DEFAULT NULL,
  `aktif` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id_kategori`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `kategori_barang` (23 rows)
INSERT INTO `kategori_barang` (`id_kategori`, `kode_kategori`, `nama_kategori`, `aktif`) VALUES
('1', 'KAT0001', 'Umum', '1'),
('2', 'KAT0002', 'Besi', '1'),
('4', 'KAT0003', 'Kawat', '0'),
('5', 'KAT0005', 'Kompresor Udara', '1'),
('6', 'KAT0006', 'Elektronik', '1'),
('7', 'KAT007', 'Kendaraan', '1'),
('8', 'KAT008', 'Komputer', '1'),
('9', 'KAT009', 'Laptop', '1'),
('10', 'KAT010', 'Furniture', '1'),
('11', 'KAT011', 'Kabel 2P', '1'),
('12', 'KAT012', 'Kabel 3P', '1'),
('13', 'KAT013', 'Kabel Jaringan', '1'),
('14', 'KAT014', 'Printer Kertas', '1'),
('15', 'KAT015', 'Printer 3D', '1'),
('16', 'KAT016', 'Mesin Produksi', '1'),
('17', 'KAT017', 'Alat Tulis', '1'),
('18', 'KAT018', 'Projector', '1'),
('19', 'KAT019', 'Alat Jaringan', '1'),
('20', 'KAT020', 'Set Kunci', '1'),
('21', 'KAT021', 'Safety Tools', '1'),
('22', 'KAT022', 'Tabung Gas', '1'),
('23', 'KAT0023', 'Bor Elektrik', '1'),
('24', 'KAT0024', 'Furni', '1');


-- --------------------------------------------------------
-- Table structure for table `menu_level`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `menu_level`;
CREATE TABLE `menu_level` (
  `id_levelmenu` int(11) NOT NULL AUTO_INCREMENT,
  `id_jabatan` int(11) NOT NULL,
  `kategori_menu` enum('MENU UTAMA','OPERASIONAL','MASTER DATA','LAPORAN') DEFAULT NULL,
  `nama_menu` varchar(50) DEFAULT NULL,
  `is_parent` tinyint(1) DEFAULT 1 COMMENT '1 = ya 0 tidak',
  `id_parent` int(11) DEFAULT NULL COMMENT 'isi jika bukan parent merujuk ke id_levelmenu',
  `link` text DEFAULT NULL,
  `akses` tinyint(1) DEFAULT 1 COMMENT '1 = ya 0 tidak',
  `terlihat` tinyint(1) DEFAULT 1 COMMENT '1 = ya 0 tidak',
  `created_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `icon` varchar(50) DEFAULT 'bi-circle',
  `urutan` int(11) DEFAULT 1,
  PRIMARY KEY (`id_levelmenu`),
  KEY `idx_jabatan_urutan` (`id_jabatan`,`urutan`)
) ENGINE=InnoDB AUTO_INCREMENT=209 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `menu_level` (156 rows)
INSERT INTO `menu_level` (`id_levelmenu`, `id_jabatan`, `kategori_menu`, `nama_menu`, `is_parent`, `id_parent`, `link`, `akses`, `terlihat`, `created_at`, `icon`, `urutan`) VALUES
('1', '1', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-08-20 19:53:50', 'bi-grid-1x2-fill', '1'),
('2', '1', 'OPERASIONAL', 'Request Order', '0', NULL, '/admin/pages/request_order/index.php', '1', '1', '2026-09-10 16:51:46', 'bi-file-earmark-text-fill', '2'),
('3', '1', 'OPERASIONAL', 'Buat RO Baru', '0', NULL, '/admin/pages/request_order/create.php', '1', '0', '2026-08-27 11:46:01', 'bi-plus-circle', '3'),
('4', '1', 'MASTER DATA', 'Profil Perusahaan', '0', NULL, '/admin/pages/profile/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-buildings', '4'),
('5', '1', 'MASTER DATA', 'Master Divisi', '0', NULL, '/admin/pages/divisi/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-diagram-3-fill', '5'),
('6', '1', 'MASTER DATA', 'Master Jabatan', '0', NULL, '/admin/pages/jabatan/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-briefcase-fill', '6'),
('7', '1', 'MASTER DATA', 'Master Site', '0', NULL, '/admin/pages/site/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-geo-alt-fill', '7'),
('8', '1', 'MASTER DATA', 'Master Karyawan', '0', NULL, '/admin/pages/user/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-people-fill', '8'),
('9', '1', 'MASTER DATA', 'Master Vendor', '0', NULL, '/admin/pages/vendor/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-truck', '9'),
('10', '1', 'MASTER DATA', 'Master Barang', '1', NULL, '#', '1', '1', '2026-08-20 19:53:50', 'bi-boxes', '10'),
('11', '1', 'MASTER DATA', 'Kategori', '0', '10', '/admin/pages/kategori/index.php', '1', '1', '2026-09-10 16:50:02', 'bi-tags', '1'),
('12', '1', 'MASTER DATA', 'Merk', '0', '10', '/admin/pages/merk/index.php', '1', '1', '2026-09-10 16:50:12', 'bi-bookmark-star', '2'),
('13', '1', 'MASTER DATA', 'Barang', '0', '10', '/admin/pages/barang/index.php', '1', '1', '2026-09-10 16:50:27', 'bi-box-seam', '3'),
('14', '1', 'MASTER DATA', 'Manajemen Menu', '0', '65', '/admin/pages/menu/index.php', '1', '1', '2026-08-22 12:31:34', 'bi-list-check', '12'),
('15', '2', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-08-20 19:53:50', 'bi-grid-1x2-fill', '1'),
('16', '2', 'OPERASIONAL', 'Request Order', '0', NULL, '/admin/pages/request_order/index.php', '1', '1', '2026-09-10 16:53:57', 'bi-file-earmark-text-fill', '2'),
('17', '2', 'OPERASIONAL', 'Buat RO Baru', '0', NULL, '/admin/pages/request_order/create.php', '1', '0', '2026-08-27 11:46:01', 'bi-plus-circle', '3'),
('23', '2', 'MASTER DATA', 'Master Vendor', '0', NULL, '/admin/pages/vendor/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-truck', '9'),
('24', '2', 'MASTER DATA', 'Master Barang', '1', NULL, '#', '1', '1', '2026-09-10 16:57:26', 'bi-boxes', '1'),
('25', '2', 'MASTER DATA', 'Kategori Barang', '0', '24', '/admin/pages/kategori/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-tags', '1'),
('26', '2', 'MASTER DATA', 'Merk Barang', '0', '24', '/admin/pages/merk/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-bookmark-star', '2'),
('27', '2', 'MASTER DATA', 'Katalog Barang', '0', '24', '/admin/pages/barang/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-box-seam', '3'),
('29', '3', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-08-20 19:53:50', 'bi-grid-1x2-fill', '1'),
('30', '3', 'OPERASIONAL', 'Request Order (RO)', '0', NULL, '/admin/pages/request_order/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-file-earmark-text-fill', '2'),
('31', '3', 'OPERASIONAL', 'Buat RO Baru', '0', NULL, '/admin/pages/request_order/create.php', '1', '0', '2026-08-27 11:46:01', 'bi-plus-circle', '3'),
('34', '3', 'MASTER DATA', 'Master Jabatan', '0', NULL, '/admin/pages/jabatan/index.php', '0', '0', '2026-08-20 20:10:24', 'bi-briefcase-fill', '6'),
('35', '3', 'MASTER DATA', 'Master Site', '0', NULL, '/admin/pages/site/index.php', '0', '0', '2026-08-20 20:10:21', 'bi-geo-alt-fill', '7'),
('36', '3', 'MASTER DATA', 'Master Karyawan', '0', NULL, '/admin/pages/user/index.php', '0', '0', '2026-08-20 20:10:18', 'bi-people-fill', '8'),
('37', '3', 'MASTER DATA', 'Master Vendor', '0', NULL, '/admin/pages/vendor/index.php', '0', '0', '2026-08-20 20:10:16', 'bi-truck', '9'),
('38', '3', 'MASTER DATA', 'Master Barang', '1', NULL, '#', '1', '1', '2026-09-04 16:57:37', 'bi-boxes', '10'),
('39', '3', 'MASTER DATA', 'Kategori Barang', '0', '38', '/admin/pages/kategori/index.php', '0', '0', '2026-08-20 20:10:14', 'bi-tags', '1'),
('40', '3', 'MASTER DATA', 'Merk Barang', '0', '38', '/admin/pages/merk/index.php', '0', '0', '2026-08-20 20:10:14', 'bi-bookmark-star', '2'),
('41', '3', 'MASTER DATA', 'Katalog Barang', '0', '38', '/admin/pages/barang/index.php', '1', '1', '2026-09-04 16:57:52', 'bi-box-seam', '3'),
('42', '3', 'MASTER DATA', 'Manajemen Menu', '0', NULL, '/admin/pages/menu/index.php', '0', '0', '2026-08-20 20:10:13', 'bi-list-check', '11'),
('43', '4', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-08-20 19:53:50', 'bi-grid-1x2-fill', '1'),
('44', '4', 'OPERASIONAL', 'Request Order (RO)', '0', NULL, '/admin/pages/request_order/index.php', '0', '0', '2026-08-22 13:00:43', 'bi-file-earmark-text-fill', '2'),
('45', '4', 'OPERASIONAL', 'Buat RO Baru', '0', NULL, '/admin/pages/request_order/create.php', '0', '0', '2026-08-22 13:00:44', 'bi-plus-circle', '3'),
('46', '4', 'MASTER DATA', 'Profil Perusahaan', '0', NULL, '/admin/pages/profile/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-buildings', '4'),
('47', '4', 'MASTER DATA', 'Master Divisi', '0', NULL, '/admin/pages/divisi/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-diagram-3-fill', '5'),
('48', '4', 'MASTER DATA', 'Master Jabatan', '0', NULL, '/admin/pages/jabatan/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-briefcase-fill', '6'),
('49', '4', 'MASTER DATA', 'Master Site', '0', NULL, '/admin/pages/site/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-geo-alt-fill', '7'),
('50', '4', 'MASTER DATA', 'Master Karyawan', '0', NULL, '/admin/pages/user/index.php', '1', '1', '2026-08-20 19:53:50', 'bi-people-fill', '8'),
('51', '4', 'MASTER DATA', 'Master Vendor', '0', NULL, '/admin/pages/vendor/index.php', '0', '0', '2026-08-22 13:01:11', 'bi-truck', '9'),
('52', '4', 'MASTER DATA', 'Master Barang', '1', NULL, '#', '0', '0', '2026-08-22 13:00:55', 'bi-boxes', '10'),
('53', '4', 'MASTER DATA', 'Kategori Barang', '0', '52', '/admin/pages/kategori/index.php', '0', '0', '2026-08-22 13:00:55', 'bi-tags', '1'),
('54', '4', 'MASTER DATA', 'Merk Barang', '0', '52', '/admin/pages/merk/index.php', '0', '0', '2026-08-22 13:00:55', 'bi-bookmark-star', '2'),
('55', '4', 'MASTER DATA', 'Katalog Barang', '0', '52', '/admin/pages/barang/index.php', '0', '0', '2026-08-22 13:00:55', 'bi-box-seam', '3'),
('56', '4', 'MASTER DATA', 'Manajemen Menu', '0', NULL, '/admin/pages/menu/index.php', '0', '0', '2026-08-22 13:03:22', 'bi-list-check', '11'),
('57', '1', 'MASTER DATA', 'Server SMTP', '0', '65', '/admin/pages/smtp/index.php', '1', '1', '2026-08-22 12:33:15', 'bi-envelope-at-fill', '13'),
('58', '5', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-08-22 12:17:38', 'bi-grid-1x2-fill', '1'),
('59', '5', 'MASTER DATA', 'Kategori', '0', '66', '/admin/pages/kategori/index.php', '1', '1', '2026-09-10 16:59:39', 'bi-tags', '6'),
('60', '5', 'OPERASIONAL', 'Request Order (RO)', '0', NULL, '/admin/pages/request_order/index.php', '1', '1', '2026-08-22 12:17:38', 'bi-file-earmark-text-fill', '2'),
('61', '5', 'MASTER DATA', 'Merk', '0', '66', '/admin/pages/merk/index.php', '1', '1', '2026-09-10 16:59:46', 'bi-bookmark-star', '7'),
('63', '5', 'MASTER DATA', 'Barang', '0', '66', '/admin/pages/barang/index.php', '1', '1', '2026-09-10 16:59:57', 'bi-box-seam', '8'),
('64', '5', 'MASTER DATA', 'Master Vendor', '0', NULL, '/admin/pages/vendor/index.php', '1', '1', '2026-08-22 12:57:03', 'bi-truck', '4'),
('65', '1', 'MASTER DATA', 'Pengaturan', '1', NULL, '#', '1', '1', '2026-08-22 12:46:31', 'bi-gear-fill', '11'),
('66', '5', 'MASTER DATA', 'Master Barang', '1', NULL, '#', '1', '1', '2026-08-22 12:57:12', 'bi-boxes', '5'),
('67', '1', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-08-22 13:26:44', 'bi-megaphone-fill', '2'),
('68', '4', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-08-22 13:27:56', 'bi-megaphone-fill', '2'),
('69', '3', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-08-22 13:29:04', 'bi-megaphone-fill', '2'),
('70', '2', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-08-22 13:29:29', 'bi-megaphone-fill', '2'),
('71', '5', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-08-22 13:30:09', 'bi-megaphone-fill', '2'),
('72', '1', 'OPERASIONAL', 'Purchase Order', '0', NULL, '/admin/pages/purchase_order/index.php', '1', '1', '2026-09-12 09:00:43', 'bi-cart-check', '3'),
('75', '4', 'OPERASIONAL', 'Purchase Order (PO)', '1', NULL, '/admin/pages/purchase_order/index.php', '1', '1', '2026-08-24 15:35:34', 'bi-cart-check', '3'),
('76', '5', 'OPERASIONAL', 'Purchase Order (PO)', '0', NULL, '/admin/pages/purchase_order/index.php', '1', '1', '2026-09-12 08:58:53', 'bi-cart-check', '3'),
('77', '1', 'OPERASIONAL', 'Penerimaan Barang', '0', NULL, '/admin/pages/receiving/index.php', '1', '1', '2026-08-26 09:23:10', 'bi-box-seam', '4'),
('78', '2', 'OPERASIONAL', 'Penerimaan Barang', '0', NULL, '/admin/pages/receiving/index.php', '1', '1', '2026-08-26 09:23:12', 'bi-box-seam', '4'),
('80', '4', 'OPERASIONAL', 'Penerimaan Barang', '0', NULL, '/admin/pages/receiving/index.php', '1', '1', '2026-08-26 09:23:17', 'bi-box-seam', '4'),
('82', '1', 'OPERASIONAL', 'PO Outstanding', '0', NULL, 'admin/pages/purchase_order/outstanding.php', '1', '1', '2026-09-10 16:51:05', 'bi-hourglass-split', '8'),
('85', '4', 'OPERASIONAL', 'PO Outstanding', '0', NULL, 'admin/pages/purchase_order/outstanding.php', '1', '1', '2026-08-27 11:24:44', 'bi-hourglass-split', '4'),
('86', '5', 'OPERASIONAL', 'PO Outstanding', '0', NULL, 'admin/pages/purchase_order/outstanding.php', '1', '1', '2026-09-10 16:59:04', 'bi-hourglass-split', '5'),
('87', '1', 'OPERASIONAL', 'Retur PO', '1', NULL, '/admin/pages/retur_po/index.php', '1', '1', '2026-08-27 16:08:34', 'bi-arrow-return-left', '5'),
('88', '2', 'OPERASIONAL', 'Retur Purchase', '0', NULL, '/admin/pages/retur_po/index.php', '1', '1', '2026-09-10 16:55:55', 'bi-arrow-return-left', '5'),
('90', '4', 'OPERASIONAL', 'Retur PO', '1', NULL, '/admin/pages/retur_po/index.php', '1', '1', '2026-08-27 16:08:34', 'bi-arrow-return-left', '5'),
('92', '1', 'OPERASIONAL', 'Faktur Purchase', '0', NULL, '/admin/pages/faktur_po/index.php', '1', '1', '2026-09-10 16:52:27', 'bi-receipt-cutoff', '6'),
('95', '4', 'OPERASIONAL', 'Faktur PO', '0', '0', '/admin/pages/faktur_po/index.php', '1', '1', '2026-08-29 10:31:02', 'bi-receipt-cutoff', '6'),
('96', '5', 'OPERASIONAL', 'Faktur Purchase', '0', NULL, '/admin/pages/faktur_po/index.php', '1', '1', '2026-09-10 16:59:20', 'bi-receipt-cutoff', '4'),
('97', '1', 'OPERASIONAL', 'Pembayaran PO', '0', '0', '/admin/pages/pembayaran_po/index.php', '1', '1', '2026-08-29 13:56:27', 'bi-cash-coin', '7'),
('100', '4', 'OPERASIONAL', 'Pembayaran PO', '0', '0', '/admin/pages/pembayaran_po/index.php', '1', '1', '2026-08-29 13:56:27', 'bi-cash-coin', '7'),
('102', '6', 'OPERASIONAL', 'Pembayaran Purchase', '0', NULL, '/admin/pages/pembayaran_po/index.php', '1', '1', '2026-09-08 10:44:29', 'bi-cash-coin', '2'),
('103', '1', 'MASTER DATA', 'Atur Timezone', '0', '65', '/admin/pages/timezone/index.php', '1', '1', '2026-09-05 13:56:34', 'bi-clock-history', '14'),
('104', '1', 'OPERASIONAL', 'Tagihan Jatuh Tempo', '0', NULL, '/admin/pages/pembayaran_po/tagihan_jatuh_tempo.php', '1', '1', '2026-09-14 12:07:14', 'bi bi-clock-history', '10'),
('105', '4', 'OPERASIONAL', 'Tagihan Jatuh Tempo', '1', '0', '/admin/pages/pembayaran_po/tagihan_jatuh_tempo.php', '1', '1', '2026-09-08 09:28:10', 'bi bi-clock-history', '98'),
('106', '6', 'OPERASIONAL', 'Tagihan Jatuh Tempo', '0', NULL, '/admin/pages/pembayaran_po/tagihan_jatuh_tempo.php', '1', '1', '2026-09-08 10:46:34', 'bi bi-clock-history', '1'),
('107', '7', 'OPERASIONAL', 'Tagihan Jatuh Tempo', '1', NULL, '#', '1', '1', '2026-09-10 16:35:07', 'bi bi-clock-history', '2'),
('108', '6', 'MENU UTAMA', 'Dashboard', '0', NULL, '/admin/dashboard.php', '1', '1', '2026-09-08 11:09:49', 'bi-grid-1x2-fill', '1'),
('109', '6', 'MENU UTAMA', 'Pengumuman', '0', NULL, '/admin/pages/info/index.php', '1', '1', '2026-09-08 11:15:12', 'bi-megaphone-fill', '2'),
('110', '6', 'OPERASIONAL', 'Edit Profil', '0', NULL, 'admin/pages/user/profile.php', '1', '0', '2026-09-08 11:16:43', 'bi bi-person-square', '3'),
('111', '1', 'MASTER DATA', 'Rekening Bank', '0', NULL, '/admin/pages/rekening_bank/index.php', '1', '1', '2026-09-15 11:01:50', 'bi-credit-card', '17'),
('113', '3', 'MASTER DATA', 'Rekening Bank', '1', NULL, '/admin/pages/rekening_bank/index.php', '0', '0', '2026-09-08 12:17:24', 'bi-credit-card', '12'),
('114', '4', 'MASTER DATA', 'Rekening Bank', '1', NULL, '/admin/pages/rekening_bank/index.php', '0', '0', '2026-09-08 12:17:24', 'bi-credit-card', '12'),
('116', '6', 'MASTER DATA', 'Rekening Bank', '0', NULL, '/admin/pages/rekening_bank/index.php', '1', '1', '2026-09-15 10:59:30', 'bi-credit-card', '1'),
('117', '7', 'MASTER DATA', 'Rekening Bank', '1', NULL, '#', '1', '1', '2026-09-10 16:35:30', 'bi-credit-card', '3'),
('118', '1', 'LAPORAN', 'Log Aktivitas', '0', NULL, '/admin/pages/activity_log/index.php', '1', '1', '2026-09-14 12:48:48', 'bi-clock-history', '27'),
('120', '4', 'LAPORAN', 'Log Aktivitas', '0', '0', '/admin/pages/activity_log/index.php', '1', '1', '2026-09-09 12:12:37', 'bi-clock-history', '99'),
('124', '1', 'LAPORAN', 'Pengeluaran Bank', '0', NULL, '/admin/pages/laporan/pengeluaran_bank.php', '1', '1', '2026-09-11 09:52:02', 'bi-bank', '24'),
('125', '4', 'LAPORAN', 'Pengeluaran Bank', '0', '0', '/admin/pages/laporan/pengeluaran_bank.php', '1', '1', '2026-09-09 15:32:18', 'bi-bank', '90'),
('126', '5', 'LAPORAN', 'Pengeluaran Bank', '0', NULL, '/admin/pages/laporan/pengeluaran_bank.php', '1', '1', '2026-09-10 16:33:26', 'bi-bank', '13'),
('127', '6', 'LAPORAN', 'Pengeluaran Bank', '0', NULL, '/admin/pages/laporan/pengeluaran_bank.php', '1', '1', '2026-09-10 16:46:21', 'bi-bank', '4'),
('128', '7', 'LAPORAN', 'Pengeluaran Bank', '0', NULL, '/admin/pages/laporan/pengeluaran_bank.php', '1', '1', '2026-09-10 16:37:05', 'bi-bank', '8'),
('129', '1', 'LAPORAN', 'Pembelian Vendor', '0', NULL, '/admin/pages/laporan/pembelian_vendor.php', '1', '1', '2026-09-10 16:27:46', 'bi-shop', '20'),
('130', '4', 'LAPORAN', 'Pembelian per Vendor', '0', '0', '/admin/pages/laporan/pembelian_vendor.php', '1', '1', '2026-09-09 16:14:02', 'bi-shop', '85'),
('131', '5', 'LAPORAN', 'Pembelian  Vendor', '0', NULL, '/admin/pages/laporan/pembelian_vendor.php', '1', '1', '2026-09-10 16:33:21', 'bi-shop', '12'),
('132', '6', 'LAPORAN', 'Pembelian Vendor', '0', NULL, '/admin/pages/laporan/pembelian_vendor.php', '1', '1', '2026-09-10 16:45:48', 'bi-shop', '1'),
('133', '7', 'LAPORAN', 'Pembelian Vendor', '0', NULL, '/admin/pages/laporan/pembelian_vendor.php', '1', '1', '2026-09-10 16:36:55', 'bi-shop', '5'),
('134', '1', 'LAPORAN', 'Realisasi Kuantitas', '0', NULL, '/admin/pages/laporan/realisasi_kuantitas.php', '1', '1', '2026-09-10 16:25:04', 'bi-bar-chart-fill', '18'),
('135', '4', 'LAPORAN', 'Realisasi Kuantitas', '0', '0', '/admin/pages/laporan/realisasi_kuantitas.php', '1', '1', '2026-09-09 16:33:01', 'bi-bar-chart-fill', '80'),
('136', '5', 'LAPORAN', 'Realisasi Kuantitas', '0', NULL, '/admin/pages/laporan/realisasi_kuantitas.php', '1', '1', '2026-09-10 16:33:07', 'bi-bar-chart-fill', '11'),
('139', '1', 'LAPORAN', 'Hutang Vendor', '0', NULL, '/admin/pages/laporan/hutang_vendor.php', '1', '1', '2026-09-11 09:51:55', 'bi-journal-text', '22'),
('140', '4', 'LAPORAN', 'Hutang Vendor', '0', '0', '/admin/pages/laporan/hutang_vendor.php', '1', '1', '2026-09-09 17:00:44', 'bi-journal-text', '75'),
('142', '6', 'LAPORAN', 'Hutang Vendor', '0', NULL, '/admin/pages/laporan/hutang_vendor.php', '1', '1', '2026-09-10 16:46:16', 'bi-journal-text', '3'),
('143', '7', 'LAPORAN', 'Hutang Vendor', '0', NULL, '/admin/pages/laporan/hutang_vendor.php', '1', '1', '2026-09-10 16:36:27', 'bi-journal-text', '7'),
('144', '1', 'LAPORAN', 'Purchase Aging', '0', NULL, '/admin/pages/laporan/purchase_aging.php', '1', '1', '2026-09-10 16:25:29', 'bi-hourglass-split', '19'),
('145', '4', 'LAPORAN', 'Purchase Aging', '0', '0', '/admin/pages/laporan/purchase_aging.php', '1', '1', '2026-09-09 17:50:58', 'bi-hourglass-split', '70'),
('146', '5', 'LAPORAN', 'Purchase Aging', '0', NULL, '/admin/pages/laporan/purchase_aging.php', '1', '1', '2026-09-10 16:32:59', 'bi-hourglass-split', '10'),
('149', '1', 'LAPORAN', 'Pembatalan', '0', NULL, '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-11 09:51:59', 'bi-x-octagon', '23'),
('150', '2', 'LAPORAN', 'Pembatalan', '0', NULL, '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-11 10:18:06', 'bi-x-octagon', '4'),
('152', '4', 'LAPORAN', 'Laporan Pembatalan', '0', '0', '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-09 21:36:44', 'bi-x-octagon', '95'),
('153', '5', 'LAPORAN', 'Laporan Pembatalan', '0', NULL, '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-10 16:33:35', 'bi-x-octagon', '14'),
('154', '6', 'LAPORAN', 'Pembatalan', '0', NULL, '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-10 16:46:03', 'bi-x-octagon', '2'),
('155', '7', 'LAPORAN', 'Pembatalan', '0', NULL, '/admin/pages/laporan/pembatalan_transaksi.php', '1', '1', '2026-09-10 16:36:00', 'bi-x-octagon', '6'),
('156', '1', 'LAPORAN', 'Data Barang-Site', '0', NULL, '/admin/pages/laporan/barang_site.php', '1', '1', '2026-09-10 16:24:24', 'bi-boxes', '16'),
('157', '2', 'LAPORAN', 'Data Barang-Site', '0', NULL, '/admin/pages/laporan/barang_site.php', '1', '1', '2026-09-11 10:18:00', 'bi-boxes', '1'),
('158', '4', 'LAPORAN', 'Data Barang per Site', '0', '0', '/admin/pages/laporan/barang_site.php', '1', '1', '2026-09-10 11:29:45', 'bi-boxes', '98'),
('162', '1', 'OPERASIONAL', 'Mutasi Barang', '0', NULL, 'admin/pages/mutasi_barang/index.php', '1', '1', '2026-09-10 16:51:14', 'bi-arrow-left-right', '9'),
('163', '1', 'LAPORAN', 'Barang Keluar', '0', NULL, 'admin/pages/laporan/barang_keluar.php', '1', '1', '2026-09-10 16:24:46', 'bi-box-arrow-right', '17'),
('164', '2', 'OPERASIONAL', 'Mutasi Barang', '0', NULL, 'admin/pages/mutasi_barang/index.php', '1', '1', '2026-09-10 16:56:34', 'bi-arrow-left-right', '6'),
('165', '2', 'LAPORAN', 'Barang Keluar', '0', NULL, 'admin/pages/laporan/barang_keluar.php', '1', '1', '2026-09-11 10:18:04', 'bi-box-arrow-right', '2'),
('168', '4', 'OPERASIONAL', 'Mutasi Barang', '0', NULL, 'admin/pages/mutasi_barang/index.php', '1', '1', '2026-09-10 12:37:28', 'bi-arrow-left-right', '4'),
('169', '4', 'LAPORAN', 'Laporan Barang Keluar', '0', NULL, 'admin/pages/laporan/barang_keluar.php', '1', '1', '2026-09-10 12:37:28', 'bi-box-arrow-right', '8'),
('174', '7', 'OPERASIONAL', 'Mutasi Barang', '0', NULL, 'admin/pages/mutasi_barang/index.php', '1', '1', '2026-09-10 16:34:50', 'bi-arrow-left-right', '1'),
('176', '1', 'LAPORAN', 'Rekap Retur PO', '0', NULL, '/admin/pages/laporan/retur_pembelian.php', '1', '1', '2026-09-11 09:51:35', 'bi-arrow-return-left', '21'),
('177', '2', 'LAPORAN', 'Retur Pembelian', '0', '0', '/admin/pages/laporan/retur_pembelian.php', '1', '1', '2026-09-11 10:18:07', 'bi-arrow-return-left', '3'),
('178', '3', 'LAPORAN', 'Laporan Retur Pembelian', '0', '0', '/admin/pages/laporan/retur_pembelian.php', '1', '1', '2026-09-11 08:37:22', 'bi-arrow-return-left', '96'),
('179', '4', 'LAPORAN', 'Laporan Retur Pembelian', '0', '0', '/admin/pages/laporan/retur_pembelian.php', '1', '1', '2026-09-11 08:37:22', 'bi-arrow-return-left', '100'),
('180', '5', 'LAPORAN', 'Laporan Retur Pembelian', '0', '0', '/admin/pages/laporan/retur_pembelian.php', '1', '1', '2026-09-11 08:37:22', 'bi-arrow-return-left', '15'),
('188', '1', 'MASTER DATA', 'Backup & Restore', '0', '65', '/admin/pages/backup/index.php', '1', '1', '2026-09-11 16:07:06', 'bi-database-gear', '15'),
('189', '2', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '0', '0', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('190', '3', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '0', '0', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('191', '4', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '1', '1', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('192', '5', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '0', '0', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('193', '6', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '1', '1', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('194', '7', 'MASTER DATA', 'Backup & Restore', '0', '0', '/admin/pages/backup/index.php', '1', '1', '2026-09-11 11:08:10', 'bi-database-gear', '99'),
('195', '1', 'LAPORAN', 'PPN Masukan', '0', NULL, '/admin/pages/laporan/pajak_masukan.php', '1', '1', '2026-09-14 12:49:09', 'bi-receipt-cutoff', '26'),
('196', '6', 'LAPORAN', 'PPN Masukan', '0', NULL, '/admin/pages/laporan/pajak_masukan.php', '1', '1', '2026-09-14 12:50:27', 'bi-receipt-cutoff', '6'),
('197', '7', '', 'Pajak Masukan', '1', '0', '/admin/pages/laporan/pajak_masukan.php', '1', '1', '2026-09-14 11:11:48', 'bi-receipt-cutoff', '9'),
('198', '1', 'LAPORAN', 'Pengeluaran Lainnya', '0', NULL, '/admin/pages/laporan/pengeluaran_lain.php', '1', '1', '2026-09-14 12:49:23', 'bi-cash-coin', '25'),
('199', '6', 'LAPORAN', 'Pengeluaran Lainnya', '0', NULL, '/admin/pages/laporan/pengeluaran_lain.php', '1', '1', '2026-09-14 12:50:19', 'bi-cash-coin', '5'),
('200', '7', '', 'Pengeluaran Lain-lain', '1', '0', '/admin/pages/laporan/pengeluaran_lain.php', '1', '1', '2026-09-14 12:43:31', 'bi-wallet2', '9'),
('201', '1', 'OPERASIONAL', 'Adjustment Stok', '0', NULL, '/admin/pages/adjustment_stok/index.php', '1', '1', '2026-09-15 10:58:25', 'bi-sliders2', '11'),
('202', '2', '', 'Adjustment Stok', '0', '0', '/admin/pages/adjustment_stok/index.php', '1', '1', '2026-09-14 15:11:39', 'bi-sliders2', '15'),
('203', '3', 'OPERASIONAL', 'Adjustment Stok', '0', NULL, '/admin/pages/adjustment_stok/index.php', '1', '1', '2026-09-14 15:15:09', 'bi-sliders2', '4'),
('204', '4', '', 'Adjustment Stok', '0', '0', '/admin/pages/adjustment_stok/index.php', '1', '1', '2026-09-14 15:11:39', 'bi-sliders2', '15'),
('205', '5', '', 'Adjustment Stok', '0', '0', '/admin/pages/adjustment_stok/index.php', '0', '0', '2026-09-14 15:11:39', 'bi-sliders2', '15'),
('207', '7', '', 'Adjustment Stok', '0', '0', '/admin/pages/adjustment_stok/index.php', '1', '1', '2026-09-14 15:11:39', 'bi-sliders2', '15'),
('208', '1', 'MASTER DATA', 'Format Penomoran', '0', '65', '/admin/pages/penomoran/index.php', '1', '1', '2026-09-15 10:52:21', 'bi-123', '16');


-- --------------------------------------------------------
-- Table structure for table `merk_barang`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `merk_barang`;
CREATE TABLE `merk_barang` (
  `id_merk` int(11) NOT NULL AUTO_INCREMENT,
  `kode_merk` varchar(10) DEFAULT NULL,
  `nama_merk` varchar(30) DEFAULT NULL,
  `aktif` tinyint(4) DEFAULT 1,
  PRIMARY KEY (`id_merk`)
) ENGINE=InnoDB AUTO_INCREMENT=168 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `merk_barang` (167 rows)
INSERT INTO `merk_barang` (`id_merk`, `kode_merk`, `nama_merk`, `aktif`) VALUES
('1', 'MRK0001', 'Umum', '1'),
('2', 'MRK0002', 'Top Cer', '1'),
('3', 'MRK0003', 'Lakoni', '1'),
('4', 'MRK0004', 'Samsung', '1'),
('5', 'MRK0005', 'LG', '1'),
('6', 'MRK0006', 'Sony', '1'),
('7', 'MRK0007', 'Panasonic', '1'),
('8', 'MRK0008', 'Sharp', '1'),
('9', 'MRK0009', 'Toshiba', '1'),
('10', 'MRK0010', 'Philips', '1'),
('11', 'MRK0011', 'Polytron', '1'),
('12', 'MRK0012', 'Aqua', '1'),
('13', 'MRK0013', 'Sanken', '1'),
('14', 'MRK0014', 'Miyako', '1'),
('15', 'MRK0015', 'Cosmos', '1'),
('16', 'MRK0016', 'Maspion', '1'),
('17', 'MRK0017', 'Modena', '1'),
('18', 'MRK0018', 'Electrolux', '1'),
('19', 'MRK0019', 'Midea', '1'),
('20', 'MRK0020', 'Daikin', '1'),
('21', 'MRK0021', 'Gree', '1'),
('22', 'MRK0022', 'Hitachi', '1'),
('23', 'MRK0023', 'Mitsubishi', '1'),
('24', 'MRK0024', 'Fujitsu', '1'),
('25', 'MRK0025', 'Sanken', '1'),
('26', 'MRK0026', 'Ariston', '1'),
('27', 'MRK0027', 'Rinnai', '1'),
('28', 'MRK0028', 'Shimizu', '1'),
('29', 'MRK0029', 'KDK', '1'),
('30', 'MRK0030', 'Oxone', '1'),
('31', 'MRK0031', 'Maxim', '1'),
('32', 'MRK0032', 'Sekai', '1'),
('33', 'MRK0033', 'Kirito', '1'),
('34', 'MRK0034', 'Advance', '1'),
('35', 'MRK0035', 'Polytron', '1'),
('36', 'MRK0036', 'TCL', '1'),
('37', 'MRK0037', 'Hisense', '1'),
('38', 'MRK0038', 'Changhong', '1'),
('39', 'MRK0039', 'Coocaa', '1'),
('40', 'MRK0040', 'AOC', '1'),
('41', 'MRK0041', 'BenQ', '1'),
('42', 'MRK0042', 'Epson', '1'),
('43', 'MRK0043', 'Canon', '1'),
('44', 'MRK0044', 'Nikon', '1'),
('45', 'MRK0045', 'Brother', '1'),
('46', 'MRK0046', 'Ricoh', '1'),
('47', 'MRK0047', 'Kyocera', '1'),
('48', 'MRK0048', 'Xiaomi', '1'),
('49', 'MRK0049', 'Realme', '1'),
('50', 'MRK0050', 'Oppo', '1'),
('51', 'MRK0051', 'Vivo', '1'),
('52', 'MRK0052', 'Huawei', '1'),
('53', 'MRK0053', 'OnePlus', '1'),
('54', 'MRK0054', 'Nokia', '1'),
('55', 'MRK0055', 'ZTE', '1'),
('56', 'MRK0056', 'TP-Link', '1'),
('57', 'MRK0057', 'D-Link', '1'),
('58', 'MRK0058', 'Tenda', '1'),
('59', 'MRK0059', 'Ubiquiti', '1'),
('60', 'MRK0060', 'MikroTik', '1'),
('61', 'MRK0061', 'Hikvision', '1'),
('62', 'MRK0062', 'Dahua', '1'),
('63', 'MRK0063', 'Ezviz', '1'),
('64', 'MRK0064', 'Imou', '1'),
('65', 'MRK0065', 'JBL', '1'),
('66', 'MRK0066', 'Yamaha', '1'),
('67', 'MRK0067', 'Denon', '1'),
('68', 'MRK0068', 'Pioneer', '1'),
('69', 'MRK0069', 'Kenwood', '1'),
('70', 'MRK0070', 'JVC', '1'),
('71', 'MRK0071', 'Bose', '1'),
('72', 'MRK0072', 'Harman Kardon', '1'),
('73', 'MRK0073', 'Marshall', '1'),
('74', 'MRK0074', 'Logitech', '1'),
('75', 'MRK0075', 'Razer', '1'),
('76', 'MRK0076', 'Acer', '1'),
('77', 'MRK0077', 'Asus', '1'),
('78', 'MRK0078', 'Lenovo', '1'),
('79', 'MRK0079', 'HP', '1'),
('80', 'MRK0080', 'Dell', '1'),
('81', 'MRK0081', 'MSI', '1'),
('82', 'MRK0082', 'Gigabyte', '1'),
('83', 'MRK0083', 'ASRock', '1'),
('84', 'MRK0084', 'Intel', '1'),
('85', 'MRK0085', 'AMD', '1'),
('86', 'MRK0086', 'Nvidia', '1'),
('87', 'MRK0087', 'Kingston', '1'),
('88', 'MRK0088', 'Transcend', '1'),
('89', 'MRK0089', 'Sandisk', '1'),
('90', 'MRK0090', 'Western Digital', '1'),
('91', 'MRK0091', 'Seagate', '1'),
('92', 'MRK0092', 'Toshiba Storage', '1'),
('93', 'MRK0093', 'TeamGroup', '1'),
('94', 'MRK0094', 'Corsair', '1'),
('95', 'MRK0095', 'FSP', '1'),
('96', 'MRK0096', 'Cooler Master', '1'),
('97', 'MRK0097', 'Thermaltake', '1'),
('98', 'MRK0098', 'NZXT', '1'),
('99', 'MRK0099', 'Deepcool', '1'),
('100', 'MRK0100', 'Arctic', '1'),
('101', 'MRK0101', 'Bosch', '1'),
('102', 'MRK0102', 'Stanley', '1'),
('103', 'MRK0103', 'DeWalt', '1'),
('104', 'MRK0104', 'Makita', '1'),
('105', 'MRK0105', 'Milwaukee', '1'),
('106', 'MRK0106', 'Black+Decker', '1'),
('107', 'MRK0107', 'Metabo', '1'),
('108', 'MRK0108', 'Hitachi Power Tools', '1'),
('109', 'MRK0109', 'Hikoki', '1'),
('110', 'MRK0110', 'Ryobi', '1'),
('111', 'MRK0111', 'Dremel', '1'),
('112', 'MRK0112', 'Skil', '1'),
('113', 'MRK0113', 'Wera', '1'),
('114', 'MRK0114', 'Knipex', '1'),
('115', 'MRK0115', 'Bahco', '1'),
('116', 'MRK0116', 'Facom', '1'),
('117', 'MRK0117', 'Gedore', '1'),
('118', 'MRK0118', 'Snap-on', '1'),
('119', 'MRK0119', 'Craftsman', '1'),
('120', 'MRK0120', 'Tekiro', '1'),
('121', 'MRK0121', 'Kenmaster', '1'),
('122', 'MRK0122', 'Kenji', '1'),
('123', 'MRK0123', 'Krisbow', '1'),
('124', 'MRK0124', 'Jakemy', '1'),
('125', 'MRK0125', 'Tactix', '1'),
('126', 'MRK0126', 'Prohex', '1'),
('127', 'MRK0127', 'Multipro', '1'),
('128', 'MRK0128', 'Kyoritsu', '1'),
('129', 'MRK0129', 'Fluke', '1'),
('130', 'MRK0130', 'Hioki', '1'),
('131', 'MRK0131', 'Karcher', '1'),
('132', 'MRK0132', 'Stihl', '1'),
('133', 'MRK0133', 'Husqvarna', '1'),
('134', 'MRK0134', 'Honda', '1'),
('135', 'MRK0135', 'Yamaha Motor', '1'),
('136', 'MRK0136', 'Kawasaki', '1'),
('137', 'MRK0137', 'Suzuki', '1'),
('138', 'MRK0138', 'Krisbow Professional', '1'),
('139', 'MRK0139', 'Informa', '1'),
('140', 'MRK0140', 'IKEA', '1'),
('141', 'MRK0141', 'Olympic', '1'),
('142', 'MRK0142', 'Ligna', '1'),
('143', 'MRK0143', 'Chitose', '1'),
('144', 'MRK0144', 'Indachi', '1'),
('145', 'MRK0145', 'Vinoti', '1'),
('146', 'MRK0146', 'Vivere', '1'),
('147', 'MRK0147', 'HighPoint', '1'),
('148', 'MRK0148', 'Steelcase', '1'),
('149', 'MRK0149', 'Herman Miller', '1'),
('150', 'MRK0150', 'Stramm', '1'),
('151', 'MRK0151', 'Donati', '1'),
('152', 'MRK0152', 'Ichiko', '1'),
('153', 'MRK0153', 'Savello', '1'),
('154', 'MRK0154', 'Chairman', '1'),
('155', 'MRK0155', 'Oscar Living', '1'),
('156', 'MRK0156', 'Dekoruma', '1'),
('157', 'MRK0157', 'Atria', '1'),
('158', 'MRK0158', 'Fabelio', '1'),
('159', 'MRK0159', 'Informa Furniture', '1'),
('160', 'MRK0160', 'Ace Hardware', '1'),
('161', 'MRK0161', 'Scandia', '1'),
('162', 'MRK0162', 'Spring Air', '1'),
('163', 'MRK0163', 'Comforta', '1'),
('164', 'MRK0164', 'Homedoki', '1'),
('165', 'MRK0165', 'Toto', '1'),
('166', 'MRK0166', 'Belden', '1'),
('167', 'MRK0167', 'Toyota', '1');


-- --------------------------------------------------------
-- Table structure for table `mutasi_order`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `mutasi_order`;
CREATE TABLE `mutasi_order` (
  `id_mutasi` int(11) NOT NULL AUTO_INCREMENT,
  `tanggal_mutasi` datetime DEFAULT NULL,
  `kode_mutasi` varchar(15) DEFAULT NULL COMMENT 'DI-YYMM-00000',
  `nomor_surat_mutasi` varchar(20) DEFAULT NULL COMMENT 'opsional',
  `id_karyawan` int(11) NOT NULL COMMENT 'yang menginputkan data',
  `id_karyawan_request` int(11) NOT NULL COMMENT 'yang meminta mutasi',
  `id_karyawan_approved` int(11) DEFAULT NULL COMMENT 'yang menyetujui',
  `id_site_asal` int(11) DEFAULT NULL,
  `id_site_tujuan` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `status` enum('DRAFT','MENUNGGU PERSETUJUAN','DISETUJUI','DITERIMA SITE TUJUAN','DIKIRIM SITE ASAL','BATAL') DEFAULT 'DRAFT',
  `biaya_operasional` double DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  PRIMARY KEY (`id_mutasi`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `mutasi_order_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `mutasi_order_detail`;
CREATE TABLE `mutasi_order_detail` (
  `id_mutasi_detail` int(11) NOT NULL,
  `id_mutasi` int(11) NOT NULL,
  `id_barang` int(11) DEFAULT NULL,
  `qty` double DEFAULT NULL,
  PRIMARY KEY (`id_mutasi_detail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `otp_verification`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `otp_verification`;
CREATE TABLE `otp_verification` (
  `id_otp` int(11) NOT NULL AUTO_INCREMENT,
  `user_type` enum('karyawan','users') NOT NULL DEFAULT 'karyawan',
  `id_user` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `otp_code` varchar(6) NOT NULL,
  `action_type` varchar(50) NOT NULL DEFAULT 'CHANGE_PASSWORD',
  `attempts` int(11) NOT NULL DEFAULT 0,
  `is_used` tinyint(1) NOT NULL DEFAULT 0,
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id_otp`),
  KEY `idx_user_action` (`user_type`,`id_user`,`action_type`),
  KEY `idx_otp_expires` (`otp_code`,`expires_at`,`is_used`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `otp_verification` (2 rows)
INSERT INTO `otp_verification` (`id_otp`, `user_type`, `id_user`, `email`, `otp_code`, `action_type`, `attempts`, `is_used`, `expires_at`, `created_at`) VALUES
('9', 'users', '1', 'itdev.nuansa@gmail.com', '287216', 'BACKUP_DATABASE', '0', '1', '2026-09-11 15:44:35', '2026-09-11 15:29:35'),
('10', 'users', '1', 'itdev.nuansa@gmail.com', '557003', 'BACKUP_DATABASE', '0', '1', '2026-09-15 13:05:18', '2026-09-15 12:50:18');


-- --------------------------------------------------------
-- Table structure for table `payment_purchase`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `payment_purchase`;
CREATE TABLE `payment_purchase` (
  `id_pembayaran` int(11) NOT NULL AUTO_INCREMENT,
  `id_faktur` int(11) DEFAULT NULL,
  `status_pembayaran` tinyint(4) DEFAULT 0 COMMENT '1=lunas , 0 = belum',
  `jenis_pembayaran` tinyint(4) DEFAULT NULL COMMENT '1=1x bayar, 0=kredit',
  `total_diskon` double NOT NULL DEFAULT 0,
  `total_bayar` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_pembayaran`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `payment_purchase_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `payment_purchase_detail`;
CREATE TABLE `payment_purchase_detail` (
  `id_pembayaran_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_pembayaran` int(11) NOT NULL,
  `kode_pembayaran` varchar(15) DEFAULT NULL,
  `tanggal_bayar` datetime DEFAULT NULL,
  `id_karyawan` int(11) NOT NULL COMMENT 'petugas admin yang input',
  `id_karyawan_approved` int(11) DEFAULT NULL,
  `bank_pengirim` varchar(30) DEFAULT NULL COMMENT 'bank yang mentransfer',
  `norek_pengirim` varchar(30) DEFAULT NULL,
  `an_pengirim` varchar(30) DEFAULT NULL COMMENT 'atas nama',
  `nominal_pengiriman` double DEFAULT NULL,
  `nominal_diskon` double NOT NULL DEFAULT 0,
  `keterangan_diskon` varchar(255) DEFAULT NULL,
  `biaya_admin` double DEFAULT NULL,
  `no_ref` varchar(30) DEFAULT NULL COMMENT 'bukti tranfser berhasil',
  `file_bukti_bayar` varchar(255) DEFAULT NULL,
  `sisa_piutang` double DEFAULT NULL COMMENT 'sisa piutang kredit pembelian',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `keterangan` text DEFAULT NULL,
  `bank_tujuan` varchar(30) DEFAULT NULL,
  `norek_tujuan` varchar(30) DEFAULT NULL,
  `an_pengiriman` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id_pembayaran_detail`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `pembatalan_transaksi`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `pembatalan_transaksi`;
CREATE TABLE `pembatalan_transaksi` (
  `id_pembatalan` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_bap` varchar(50) NOT NULL,
  `jenis_dokumen` enum('PO','FAKTUR') NOT NULL,
  `id_referensi` int(11) NOT NULL,
  `nomor_referensi` varchar(50) NOT NULL,
  `state_tahapan` varchar(100) NOT NULL,
  `id_vendor` int(11) DEFAULT NULL,
  `nama_vendor` varchar(255) DEFAULT NULL,
  `nilai_transaksi` decimal(15,2) DEFAULT 0.00,
  `kategori_alasan` varchar(100) NOT NULL,
  `alasan_detail` text NOT NULL,
  `id_karyawan_batal` int(11) DEFAULT NULL,
  `nama_karyawan_batal` varchar(100) NOT NULL,
  `tanggal_batal` datetime NOT NULL,
  `email_notif_sent` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id_pembatalan`),
  UNIQUE KEY `nomor_bap` (`nomor_bap`),
  KEY `idx_jenis_ref` (`jenis_dokumen`,`id_referensi`),
  KEY `idx_nomor_bap` (`nomor_bap`),
  KEY `idx_tanggal` (`tanggal_batal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `penomoran`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `penomoran`;
CREATE TABLE `penomoran` (
  `id_nomor` int(11) NOT NULL AUTO_INCREMENT,
  `nama_penomoran` varchar(50) DEFAULT NULL,
  `tipe_transaksi` enum('REQUEST','PURCHASE','RECEIVING','RETUR PO','FAKTUR PO','PAYMENT PO','MUTASI BARANG','ADJUSTMENT STOK') DEFAULT NULL,
  `tipe_penomoran` tinyint(1) DEFAULT 0 COMMENT '0 = tidak reset, 1 reset harian, 2 reset bulanan, 3 reset tahuan',
  `digit_counter` tinyint(1) DEFAULT NULL COMMENT 'misal 3 = 003, 013. misal 5 = 00005, 00010',
  `format` varchar(60) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `id_karyawan` int(11) NOT NULL,
  PRIMARY KEY (`id_nomor`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `penomoran` (8 rows)
INSERT INTO `penomoran` (`id_nomor`, `nama_penomoran`, `tipe_transaksi`, `tipe_penomoran`, `digit_counter`, `format`, `created_at`, `updated_at`, `id_karyawan`) VALUES
('3', 'Permintaan Pesanan', 'REQUEST', '2', '5', 'PO/[SHORT_YEAR][MONTH][DAY]/[COUNTER]', '2026-09-15 11:44:02', '2026-09-15 12:42:54', '1'),
('4', 'Pesanan Pembelian', 'PURCHASE', '2', '4', 'PR/[SHORT_YEAR][MONTH][DAY]-[COUNTER]', '2026-09-15 12:26:16', '2026-09-15 12:42:42', '1'),
('5', 'Penerimaan', 'RECEIVING', '1', '4', 'PN/[SHORT_YEAR][MONTH][DAY]/[COUNTER]', '2026-09-15 12:29:46', NULL, '1'),
('6', 'Retur', 'RETUR PO', '1', '4', 'RT/[COUNTER]/[SHORT_YEAR][MONTH][DAY]', '2026-09-15 12:32:27', NULL, '1'),
('7', 'Faktur Invoice', 'FAKTUR PO', '2', '3', 'FP[SHORT_YEAR]/[MONTH][DAY]/[COUNTER]', '2026-09-15 12:35:26', '2026-09-15 12:40:43', '1'),
('8', 'Pembayaran', 'PAYMENT PO', '2', '3', 'PF[SHORT_YEAR]/[MONTH][DAY]/[COUNTER]', '2026-09-15 12:39:15', '2026-09-15 12:39:38', '1'),
('9', 'Mutasi Barang', 'MUTASI BARANG', '2', '5', 'DI-[SHORT_YEAR][MONTH]-[COUNTER]', '2026-09-15 12:44:59', NULL, '1'),
('10', 'Penyesuaian Stock', 'ADJUSTMENT STOK', '2', '5', 'ADJ-[SHORT_YEAR][MONTH]-[COUNTER]', '2026-09-15 12:46:13', NULL, '1');


-- --------------------------------------------------------
-- Table structure for table `profile`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `profile`;
CREATE TABLE `profile` (
  `id_perusahaan` int(11) NOT NULL,
  `nama` varchar(60) DEFAULT NULL,
  `telepon1` varchar(30) DEFAULT NULL,
  `whatsapp` varchar(30) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `alamat` text DEFAULT NULL,
  `alamat_gps` varchar(50) DEFAULT NULL,
  `kota` varchar(50) DEFAULT NULL,
  `provinsi` varchar(50) DEFAULT NULL,
  `npwp` varchar(30) DEFAULT NULL,
  `KLU` varchar(30) DEFAULT NULL,
  `NITKU` varchar(30) DEFAULT NULL,
  `timezone` varchar(50) NOT NULL DEFAULT 'Asia/Makassar',
  `pajak12` tinyint(1) DEFAULT 1,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `picture` text DEFAULT NULL,
  PRIMARY KEY (`id_perusahaan`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `profile` (1 rows)
INSERT INTO `profile` (`id_perusahaan`, `nama`, `telepon1`, `whatsapp`, `email`, `alamat`, `alamat_gps`, `kota`, `provinsi`, `npwp`, `KLU`, `NITKU`, `timezone`, `pajak12`, `updated_at`, `picture`) VALUES
('1', 'PT Jaya Teknik', '031-889900', '081234567890', 'info@jayateknis.com', 'Jl. Ahmad Ardans', '', 'Samarinda', 'Kalimantan Timur', '01.234.567.8-604.000', 'KLU33151', '0123456789012345', 'Asia/Makassar', '0', '2026-09-07 11:12:51', 'images/uploads/company/company_logo_1788750771_f0eedc.png');


-- --------------------------------------------------------
-- Table structure for table `purchase_order`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `purchase_order`;
CREATE TABLE `purchase_order` (
  `id_po` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_po` varchar(20) DEFAULT NULL COMMENT 'PO-YYMM-0000001',
  `tanggal_po` date DEFAULT NULL,
  `id_karyawan` int(11) DEFAULT NULL COMMENT 'pembuat_purchasing_order',
  `id_site` int(11) DEFAULT NULL,
  `id_vendor` int(11) NOT NULL,
  `status` enum('DRAFT','REVIEW INTERNAL','DISETUJUI INTERNAL','TIDAK DISETUJUI INTERNAL','REVIEW VENDOR','DIPROSES VENDOR','DITERIMA','BATAL') DEFAULT NULL,
  `prioritas` enum('NORMAL','URGENT') DEFAULT NULL,
  `tanggal_status` datetime DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `alamat` text DEFAULT NULL,
  `pengiriman` enum('Vendor','Expedisi','Internal') DEFAULT NULL,
  `tanggal_pengiriman` datetime DEFAULT NULL,
  `term_of_payment` tinyint(4) DEFAULT 30 COMMENT '0 = C.O.D, >=1 adalah hari',
  `id_receiving` int(11) DEFAULT NULL,
  `id_karyawan_approved` int(11) DEFAULT NULL COMMENT 'yang menyetujui purchasing_order diambil dari karyawan.id_karyawan',
  `total_termasuk_pajak` tinyint(4) DEFAULT NULL COMMENT '1 = ya PPN',
  `pajak` tinyint(4) DEFAULT 0 COMMENT 'PPN',
  `diskon` double DEFAULT 0,
  `total_termasuk_PPnBM` tinyint(4) DEFAULT 0 COMMENT '1 = ya PPnBM',
  `pajak_PPnBM` tinyint(4) DEFAULT NULL COMMENT 'PPnBM rate',
  PRIMARY KEY (`id_po`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `purchase_order_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `purchase_order_detail`;
CREATE TABLE `purchase_order_detail` (
  `id_po_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_po` int(11) DEFAULT NULL,
  `id_barang` int(11) DEFAULT NULL,
  `qty` double DEFAULT NULL,
  `harga` double DEFAULT NULL,
  `diskon` double DEFAULT NULL,
  `subtotal` double DEFAULT NULL,
  `kena_pajak` double DEFAULT NULL COMMENT 'PPN',
  `keterangan` text DEFAULT NULL,
  `kena_pajak_ppnbm` double DEFAULT NULL,
  PRIMARY KEY (`id_po_detail`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `receiving_order`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `receiving_order`;
CREATE TABLE `receiving_order` (
  `id_rcv` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_rcv` varchar(20) DEFAULT NULL COMMENT 'RI-YYMM-0000001 / nomor SPB',
  `id_po` int(11) NOT NULL,
  `id_karyawan` int(11) DEFAULT NULL COMMENT 'diambil dari karyawan khusus logistik dan jabatannya',
  `tanggal_rcv` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `tanggal_diterima` datetime DEFAULT NULL,
  `nomor_sj` varchar(30) DEFAULT NULL COMMENT 'nomor surat jalan dari vendor',
  `file_sj` varchar(50) DEFAULT NULL COMMENT 'hnya nama file + ext',
  `keterangan` text DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL COMMENT '1=diterima semua, 0=diterima sebagian',
  `print` tinyint(1) DEFAULT NULL COMMENT '1 = ya',
  `print_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id_rcv`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `receiving_order_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `receiving_order_detail`;
CREATE TABLE `receiving_order_detail` (
  `id_rcv_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_rcv` int(11) DEFAULT NULL,
  `id_barang` varchar(255) DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `status_qc` tinyint(1) DEFAULT NULL COMMENT 'Kondisi 1=Baik,0=Rusak ',
  `keterangan` text DEFAULT NULL,
  PRIMARY KEY (`id_rcv_detail`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `rekening_bank`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `rekening_bank`;
CREATE TABLE `rekening_bank` (
  `id_bank` int(11) NOT NULL AUTO_INCREMENT,
  `nama_bank` varchar(50) DEFAULT NULL,
  `atasnama_rekening` varchar(60) DEFAULT NULL,
  `no_rekening` varchar(30) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `id_karyawan` int(11) DEFAULT NULL COMMENT 'pembuat rekening',
  PRIMARY KEY (`id_bank`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `rekening_bank` (3 rows)
INSERT INTO `rekening_bank` (`id_bank`, `nama_bank`, `atasnama_rekening`, `no_rekening`, `created_at`, `id_karyawan`) VALUES
('1', 'Bank Mandiri', 'PT JAYA TEKNIK', '1400098765432', '2026-09-08 12:21:56', '9'),
('2', 'Bank Central Asia (BCA)', 'JAYA TEKNIK SMD PT', '332519219', '2026-09-08 12:22:44', '5'),
('3', 'Tunai', NULL, NULL, '2026-09-08 14:21:08', '5');


-- --------------------------------------------------------
-- Table structure for table `request_order`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `request_order`;
CREATE TABLE `request_order` (
  `id_request` int(11) NOT NULL AUTO_INCREMENT,
  `nomor` varchar(20) DEFAULT NULL,
  `tanggal_ro` datetime DEFAULT current_timestamp(),
  `id_karyawan` int(11) DEFAULT NULL,
  `id_site` int(11) DEFAULT NULL,
  `status` enum('DRAFT','TERKIRIM','DISETUJUI LOGISTIK','TIDAK DISETUJUI LOGISTIK','DISETUJUI PURCHASING','TIDAK DISETUJUI PURCHASING','DITERIMA FULL','DITERIMA SEBAGIAN','BATAL') DEFAULT 'DRAFT',
  `prioritas` enum('NORMAL','URGENT') NOT NULL DEFAULT 'NORMAL',
  `id_vendor` int(11) DEFAULT NULL,
  `tanggal_status` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `keterangan` text DEFAULT NULL,
  `id_po` int(11) DEFAULT NULL COMMENT 'Jika sudah terbit jadi po',
  `id_karyawan_approved` int(11) DEFAULT NULL COMMENT 'khusus untuk menyetujui dari mekanik',
  PRIMARY KEY (`id_request`),
  KEY `idx_ro_status_tanggal` (`status`,`tanggal_ro`),
  KEY `idx_ro_karyawan` (`id_karyawan`),
  KEY `idx_ro_site` (`id_site`),
  KEY `idx_ro_nomor` (`nomor`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `request_order_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `request_order_detail`;
CREATE TABLE `request_order_detail` (
  `id_request_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_request` int(11) NOT NULL,
  `id_barang` int(11) DEFAULT NULL,
  `kode_barang` varchar(30) DEFAULT NULL,
  `nama_barang` varchar(60) DEFAULT NULL,
  `qty` double DEFAULT NULL,
  `satuan` varchar(30) NOT NULL DEFAULT 'PCS',
  `harga` double DEFAULT 0,
  `subtotal` double DEFAULT 0,
  PRIMARY KEY (`id_request_detail`),
  KEY `idx_rod_request` (`id_request`),
  KEY `idx_rod_barang` (`id_barang`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `retur_po`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `retur_po`;
CREATE TABLE `retur_po` (
  `id_po_retur` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_po_retur` varchar(20) DEFAULT NULL,
  `id_karyawan` int(11) DEFAULT NULL COMMENT 'pembuat karyawan logistik',
  `id_karyawan_approved` int(11) DEFAULT NULL COMMENT 'ID Pejabat Penyetuju',
  `tanggal_po_retur` datetime DEFAULT NULL,
  `kompensasi` tinyint(1) DEFAULT 1 COMMENT '1= tukar unit, 0=pengurangan piutang dan barang',
  `id_vendor` int(11) NOT NULL,
  `pic_vendor` varchar(30) DEFAULT NULL COMMENT 'karyawan vendor yang bertanggung jawab atas retur',
  `id_site` int(11) DEFAULT NULL COMMENT 'tujuan site dikirim kembali',
  `id_po` int(11) NOT NULL,
  `id_rcv` int(11) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `total` double DEFAULT NULL COMMENT 'total harga yang di retur',
  `status` enum('DRAFT','MENUNGGU KONFIRMASI VENDOR','DISETUJUI VENDOR','TIDAK DISETUJUI VENDOR','DIKIRIM KE VENDOR','DITERIMA') DEFAULT 'DRAFT',
  `nominal_pajak` double DEFAULT NULL COMMENT 'angka nominal pajak yang dibatalkan',
  `rate_pajak` tinyint(4) DEFAULT 0 COMMENT 'Tarif PPN: 0, 11, atau 12 %',
  `nomor_sj_retur` varchar(30) DEFAULT NULL,
  `nomor_nota_retur_pajak` varchar(30) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `pengiriman_retur` enum('Vendor','Expedisi','Internal') DEFAULT 'Vendor',
  `biaya_retur` double DEFAULT 0,
  PRIMARY KEY (`id_po_retur`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- --------------------------------------------------------
-- Table structure for table `retur_po_detail`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `retur_po_detail`;
CREATE TABLE `retur_po_detail` (
  `id_po_retur_detail` int(11) NOT NULL AUTO_INCREMENT,
  `id_po_retur` int(11) NOT NULL,
  `id_barang` int(11) NOT NULL,
  `qty_retur` double DEFAULT NULL,
  `satuan` varchar(20) DEFAULT 'PCS',
  `harga_satuan` double DEFAULT 0,
  `subtotal` double DEFAULT 0,
  `alasan_retur` enum('RUSAK_FISIK','CACAT_PRODUKSI','SALAH_SPESIFIKASI','KURANG_PENGIRIMAN','KADALUARSA_EXP') DEFAULT 'RUSAK_FISIK',
  `keterangan_kerusakan` text DEFAULT NULL,
  `foto_bukti` varchar(255) DEFAULT NULL COMMENT 'Path / nama file foto',
  `qty_diganti` double DEFAULT 0,
  PRIMARY KEY (`id_po_retur_detail`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- --------------------------------------------------------
-- Table structure for table `site`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `site`;
CREATE TABLE `site` (
  `id_site` int(11) NOT NULL AUTO_INCREMENT,
  `kode_site` varchar(10) DEFAULT NULL,
  `nama_site` varchar(50) DEFAULT NULL,
  `jenis_site` varchar(30) DEFAULT NULL COMMENT 'Pusat, Office, Bengkel, Logistik, Lain Lain',
  `alamat` text DEFAULT NULL,
  `alamat_gps` varchar(50) DEFAULT NULL,
  `no_hp` varchar(30) DEFAULT NULL,
  `id_karyawan_headof` int(11) DEFAULT NULL,
  `penyimpanan_stok` tinyint(4) DEFAULT 0 COMMENT '1 = ya, 0 tidak',
  PRIMARY KEY (`id_site`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `site` (4 rows)
INSERT INTO `site` (`id_site`, `kode_site`, `nama_site`, `jenis_site`, `alamat`, `alamat_gps`, `no_hp`, `id_karyawan_headof`, `penyimpanan_stok`) VALUES
('1', 'SIT01', 'Galangan Utama Dok 1', 'Bengkel', 'Jl. Pelabuhan Maritim No. 12, Surabaya', NULL, '031-889901', '5', '1'),
('2', 'SIT02', 'Workshop Bubut & Las Fabrikasi', 'Bengkel', 'Kawasan Industri Gresik Blok B-4', '', '031-889902', '2', '1'),
('3', 'SIT03', 'Gudang Logistik & Suku Cadang', 'Logistik', 'Jl. Dermaga Barat No. 8, Surabaya', NULL, '031-889903', '5', '1'),
('4', 'SIT04', 'Kantor Pusat & Operasional', 'Office', 'Jl. Perak Timur No. 100, Surabaya', '', '031-889900', '5', '1');


-- --------------------------------------------------------
-- Table structure for table `smtp_server`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `smtp_server`;
CREATE TABLE `smtp_server` (
  `id_stmp` int(11) NOT NULL AUTO_INCREMENT,
  `nama_provider` varchar(20) DEFAULT NULL,
  `link_provider` varchar(50) DEFAULT NULL,
  `stmp_server` varchar(30) DEFAULT NULL,
  `port` varchar(4) DEFAULT NULL,
  `user_login` varchar(30) DEFAULT NULL,
  `password` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `limit_harian` int(11) DEFAULT NULL COMMENT '300 perhari',
  `sisa_harian` int(11) DEFAULT NULL,
  `aktif` tinyint(4) DEFAULT 1 COMMENT '1 aktif',
  PRIMARY KEY (`id_stmp`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `smtp_server` (1 rows)
INSERT INTO `smtp_server` (`id_stmp`, `nama_provider`, `link_provider`, `stmp_server`, `port`, `user_login`, `password`, `created_at`, `limit_harian`, `sisa_harian`, `aktif`) VALUES
('1', 'Gmail SMTP', 'https://myaccount.google.com/apppasswords', 'smtp.gmail.com', '587', 'itdev.nuansa@gmail.com', 'ackrudbkucrkfnxh', '2026-08-22 09:36:07', '100', '54', '1');


-- --------------------------------------------------------
-- Table structure for table `users`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id_users` int(11) NOT NULL AUTO_INCREMENT,
  `nama_users` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `aktif` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_users`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `users` (1 rows)
INSERT INTO `users` (`id_users`, `nama_users`, `email`, `password`, `aktif`, `created_at`) VALUES
('1', 'Administrator', 'shem1990@gmail.com', '$2y$10$gXvuzhGeM6AmUDFDObJ8hOPaUp9BXUfQY77BO3cbV.v6zjRW/2Izu', '1', '2026-08-22 11:56:46');


-- --------------------------------------------------------
-- Table structure for table `vendor`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `vendor`;
CREATE TABLE `vendor` (
  `id_vendor` int(11) NOT NULL AUTO_INCREMENT,
  `kode_vendor` varchar(10) NOT NULL,
  `nama_perusahaan` varchar(60) NOT NULL,
  `alamat` text DEFAULT NULL,
  `gps_alamat` varchar(50) DEFAULT NULL,
  `no_telepon` varchar(255) DEFAULT NULL,
  `kota` varchar(50) DEFAULT NULL,
  `person` varchar(30) DEFAULT NULL,
  `kontak_person` varchar(30) DEFAULT NULL,
  `website` varchar(30) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `update_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `jenis_vendor` varchar(50) DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `aktif` tinyint(1) DEFAULT 1,
  `nomor_rekening` varchar(30) DEFAULT NULL,
  `nama_bank` varchar(255) DEFAULT NULL,
  `term_of_payment` int(11) DEFAULT NULL COMMENT 'days',
  `saldo_hutang_terakhir` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_vendor`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `vendor` (9 rows)
INSERT INTO `vendor` (`id_vendor`, `kode_vendor`, `nama_perusahaan`, `alamat`, `gps_alamat`, `no_telepon`, `kota`, `person`, `kontak_person`, `website`, `email`, `created_at`, `update_at`, `jenis_vendor`, `keterangan`, `aktif`, `nomor_rekening`, `nama_bank`, `term_of_payment`, `saldo_hutang_terakhir`) VALUES
('1', 'VND001', 'PT Baja Maritim Nusantara', 'Kawasan Industri Rungkut Surabaya', NULL, '031-778811', 'Surabaya', 'Bpk. Gunawan', NULL, NULL, NULL, '2026-08-19 22:23:08', '2026-08-20 10:46:23', 'Toko Retail', 'Supplier plat baja & profil kapal', '1', NULL, NULL, '30', '0'),
('2', 'VND002', 'CV Sumber Teknik Las & Gas', 'Jl. Kalianak Barat No. 45, Surabaya', NULL, '031-778822', 'Surabaya', 'Ibu Ratna', NULL, NULL, NULL, '2026-08-19 22:23:08', '2026-08-20 10:46:41', 'Toko Distributor', 'Distributor kawat las & perlengkapan welding', '1', NULL, NULL, '14', '0'),
('3', 'VND003', 'PT Indo Bearing & Seal Sejahtera', 'Jl. Dupak Rukun No. 88, Surabaya', NULL, '031-778833', 'Surabaya', 'Bpk. Tony', NULL, NULL, NULL, '2026-08-19 22:23:08', '2026-09-07 11:45:45', 'Bengkel', 'Bearing propeller & mechanical seal', '1', '7521883991', 'Bank Kaltimtara', '30', '0'),
('4', 'VND004', 'PT Samudera Marine Supply', 'Jl. Tanjung Perak Barat No. 20, Surabaya', NULL, '031-778844', 'Batam', 'Bpk. Eko', NULL, NULL, NULL, '2026-08-19 22:23:08', '2026-08-20 10:54:17', 'Dealer', 'Sparepart mesin diesel kapal & valve', '1', NULL, NULL, '45', '0'),
('5', 'VND005', 'Nuansa Cipta Dharma, PT', 'Jl. Untung Suropati No 35, Kel. Sungai Kunjang', '-0.520035, 117.116561', '0541898912', 'Samarinda', 'Edi Dharmawan', '081178901234 (Direktur)', 'tokonuansa.com', 'tokonuansa@gmail.com', '2026-08-27 11:58:30', NULL, 'Elektronik', '', '1', '99999', 'BCA', '15', '0'),
('6', 'VND006', 'Arena Computer', 'Jl. Bung Tomo Samarinda', 'https://maps.app.goo.gl/h8eF1syqKECC8MgFA', '0541-65313314', 'Samarinda', 'Dimas', '085286812235', '', 'aringo.kom@gmail.com', '2026-09-05 11:35:12', '2026-09-05 11:37:20', 'Komputer', '', '1', '81731111350', 'BCA', '10', '0'),
('7', 'VND007', 'Cici Jaya .CV', 'Jl. P. Antasari No 109', '', '0541-261785', 'Samarinda', 'Bagas', '085233312589', '', 'tokocici2112@gmail.com', '2026-09-07 14:55:17', NULL, 'Bangunan', '', '1', '39851156', 'BNI', '25', '0'),
('8', 'VND008', 'Informa Bigmall', 'Jl. Untung Suropati, Bigmall Lt. 2', '', '0541651234', 'Samarinda', '', '085287871111', 'ruparupa.com', '', '2026-09-08 14:47:07', '2026-09-10 09:26:25', 'Furniture', '', '1', '1150878844', 'BNI', '30', '0'),
('9', 'VND009', 'Graha Toyota Samarinda', 'Jl. Pangeran Antasari No. 22 Air Putih', '', '0541-9120013', 'Samarinda', 'Aris', '085289125555', '', 'sales.toyotasamarinda@gmail.com', '2026-09-12 10:46:04', NULL, 'Dealer Mobil', '', '1', 'GRAHA TOYOTA SMD', 'BCA', '60', '0');


SET FOREIGN_KEY_CHECKS=1;
COMMIT;
-- Dump completed on 2026-09-15 12:51:33
